### ISSUE TITLE
Migrate Spark SQL JDBC data source integration tests here

### ISSUE THREAD

**Issue by liancheng** [databricks/spark-integration-tests#6]
The Spark SQL JDBC data source comes with integration test suites which require docker. They were ignored from the very beginning because they are too time consuming to be executed in unit test phase. Subsequently, they were removed in PR apache/spark#4872 because they depend on docker-client 2.7.5, which causes dependency hell. These test suites are very useful, and should be migrated here.

**Comment by JoshRosen** [comment]
Going to close this for now, since I have successfully re-enabled these tests in Spark: https://github.com/apache/spark/pull/9503
